### ISSUE TITLE
illustrator svg file for kicad mac 201507

### ISSUE THREAD

**Issue by lolojh** [mondalaci/dxf2svg2kicad#9]
Error in kicad opening the file generated:

10:35:57: dlopen(/Applications/Kicad PCB 2015 07/kicad.app/Contents/PlugIns/_pcbnew.kiface, 10): Symbol not found: ___sincos_stret
  Referenced from: /Applications/Kicad PCB 2015 07/kicad.app/Contents/Applications/pcbnew.app/Contents/MacOS/../Frameworks/libcairo.2.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Kicad PCB 2015 07/kicad.app/Contents/Applications/pcbnew.app/Contents/MacOS/../Frameworks/libcairo.2.dylib
10:35:57: IO_ERROR: Fatal Installation Bug. File:
'/Applications/Kicad PCB 2015 07/kicad.app/Contents/PlugIns/_pcbnew.kiface'
could not be loaded
Perhaps a wxWidgets shared (.dll or .so) file is missing.
From command line: argv[0]:
'/Applications/Kicad PCB 2015 07/kicad.app/Contents/Applications/pcbnew.app/Contents/MacOS/pcbnew'

from /Users/jenkins/remoteroot/workspace/KiCadBuildMac/kicad/common/kiway.cpp : KiFACE() : line 225

![nbsi4kicad](https://cloud.githubusercontent.com/assets/13251932/8591271/5b79ed9a-2627-11e5-8006-da31badbcd21.jpg)

**Comment by mondalaci** [comment]
In order for me to help you, please attach the relevant DXF or SVG file, so that I can look into it. You can attach it here, but first rename it as JPG. (Github is stupid in this respect but it works.)

**Comment by lolojh** [comment]
Hi Laszlo,

Thank you for your quick response.
Here is it!


Stef

**Comment by mondalaci** [comment]
Chances are you attached the source file in your email client but not on Github. Please visit the URL of this issue, rename the file to JPG and attach it here. This is the only way I'll be able to see it.

**Comment by mondalaci** [comment]
Closing this issue due to the lack of activity.
